config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "admin"

  root "pages#home"
  get "pages/contact_us", as: "contactUs"
  get "pages/products", as: "products"
  get "pages/service", as: "service"
  get "pages/about", as: "about"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/admin/application_record.rb
class Admin::ApplicationRecord < ActiveRecord::Base
  include SpreadsheetArchitect; self.abstract_class = true; self.table_name_prefix = "admin_"
end

app/models/admin/current.rb
class Admin::Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/admin/user.rb
class Admin::User < Admin::ApplicationRecord
  has_secure_password

  generates_token_for :password_reset, expires_in: 20.minutes do
    password_salt.last(10)
  end

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 12 }, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/ }

  normalizes :email, with: -> { _1.strip.downcase }

  def self.ransackable_attributes(auth_object = nil)
    %w[email created_at]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [ :job_seeker, :employer ]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  include Pagy::Backend

  around_action :set_time_zone
  before_action :authenticate

  private
    def set_time_zone
      Time.use_zone(cookies[:time_zone]) { yield }
    end

    def authenticate
      if user = Admin::User.find_by_id(session[:admin_user_id])
        Admin::Current.user = user
      else
        redirect_to admin_sign_in_path
      end
    end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
  end
end

app/controllers/admin/password_resets_controller.rb
class Admin::PasswordResetsController < Admin::BaseController
  skip_before_action :authenticate

  before_action :set_user, only: %i[ edit update ]

  layout "admin/authentication"

  def new
  end

  def edit
  end

  def create
    if @user = Admin::User.find_by(email: params[:email])
      send_password_reset_email
      redirect_to admin_sign_in_path, notice: "Check your email for reset instructions"
    else
      redirect_to new_admin_password_reset_path, alert: "Sorry, we didn't recognize that email address"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_sign_in_path, notice: "Your password was reset successfully. Please sign in"
    else
      redirect_to edit_admin_password_reset_path(token: params[:token]), alert: @user.errors.first.full_message
    end
  end

  private
    def set_user
      @user = Admin::User.find_by_token_for!(:password_reset, params[:token])
    rescue StandardError
      redirect_to new_admin_password_reset_path, alert: "That password reset link is invalid"
    end

    def user_params
      params.permit(:password, :password_confirmation)
    end

    def send_password_reset_email
      Admin::UserMailer.with(user: @user).password_reset.deliver_later
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  skip_before_action :authenticate, only: %i[ new create ]

  layout "admin/authentication"

  def new
    @user = Admin::User.new
  end

  def create
    if user = Admin::User.authenticate_by(email: params[:email], password: params[:password])
      session[:admin_user_id] = user.id; redirect_to(admin_path)
    else
      redirect_to admin_sign_in_path(email_hint: params[:email]), alert: "That email or password is incorrect"
    end
  end

  def destroy
    session[:admin_user_id] = nil; redirect_to admin_sign_in_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @search = Admin::User.all.ransack(params[:q])

    respond_to do |format|
      format.html { @pagy, @users = pagy(@search.result) }
      format.csv  { render csv: @search.result }
    end
  end

  def show
  end

  def new
    @user = Admin::User.new
  end

  def edit
  end

  def create
    @user = Admin::User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "User was successfully destroyed."
  end

  private
    def set_user
      @user = Admin::User.find(params[:id])
    end

    def user_params
      params.require(:admin_user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(resource_or_scope)
    params[:return_to].presence || root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :phone_number, :address, :email, :password, :password_confirmation ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name, :phone_number, :address, :email, :password, :password_confirmation ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def products
  end

  def service
  end

  def contact_us
  end
  
  def about
  end
end

app/helpers/admin/application_helper.rb
require "pagy/extras/bootstrap"

module Admin::ApplicationHelper
  include Pagy::Frontend

  def title
    content_for(:title) || Rails.application.class.to_s.split("::").first
  end

  def active_nav_item(*names)
    names.include?(controller_path) ? "active" : ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/base/_flash_messages.html.erb
<% message = notice || alert %>

<% if message.present? %>
  <div class="position-fixed start-50 translate-middle-x" style="z-index: 1030; top: 8rem;">
    <div class="toast hide text-center text-white bg-dark border-0" data-controller="flash-message">
      <div class="toast-body">
        <%= message %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/base/_footer.html.erb
<footer class="footer footer-transparent d-print-none">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item"><a href="./docs/index.html" class="link-secondary">Documentation</a></li>
          <li class="list-inline-item"><a href="./license.html" class="link-secondary">License</a></li>
          <li class="list-inline-item"><a href="https://github.com/tabler/tabler" target="_blank" class="link-secondary" rel="noopener">Source code</a></li>
          <li class="list-inline-item">
            <a href="https://github.com/sponsors/codecalm" target="_blank" class="link-secondary" rel="noopener">
              <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink icon-filled icon-inline" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" /></svg>
              Sponsor
            </a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            Copyright &copy; 2022
            <a href="." class="link-secondary">Tabler</a>.
            All rights reserved.
          </li>
          <li class="list-inline-item">
            <a href="./changelog.html" class="link-secondary" rel="noopener">
              v1.0.0-beta6
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/admin/base/_javascript_tags.html.erb
<script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta24/dist/js/tabler.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@rails/ujs@7.1.3-4/app/assets/javascripts/rails-ujs.min.js"></script>

<!-- Stimulus -->
<script type="module">
  import { Application, Controller } from "https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.2.2/+esm"
  window.Stimulus = Application.start()

  Stimulus.register("flash-message", class extends Controller {
    connect() { new bootstrap.Toast(this.element).show() }
  })
</script>

<!-- Time zone -->
<script type="module">
  import jsCookie from "https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/+esm"
  const { timeZone } = new Intl.DateTimeFormat().resolvedOptions()
  jsCookie.set("time_zone", timeZone, { expires: 365 })
</script>

app/views/admin/base/_page_header.html.erb
<div class="container-xl">
  <div class="page-header">
    <div class="row align-items-center">
      <%= yield %>
    </div>
  </div>
</div>

app/views/admin/base/_page_header_actions.html.erb
<div class="col-auto">
  <div class="btn-list">
    <%= yield %>
  </div>
</div>

app/views/admin/base/_page_header_breadcrumb.html.erb
<%= content_for :title, title %>

<div class="col">
  <div class="mb-1">
    <ol class="breadcrumb" aria-label="breadcrumbs">
      <%= yield %>
    </ol>
  </div>
  <h1 class="page-title">
    <span class="text-truncate"><%= title %></span>
  </h1>
</div>

app/views/admin/base/_primary_navbar.html.erb
<header class="navbar navbar-expand-md navbar-light d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <%= link_to admin_path do %>
        <%= image_tag "admin/logo.svg", width: 110, height: 32, alt: "Tabler", class: "navbar-brand-image" %>
      <% end %>
    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item d-none d-md-flex me-3">
        <div class="btn-list">
          <a href="https://github.com/tabler/tabler" class="btn" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" /></svg>
            Source code
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" /></svg>
            Sponsor
          </a>
        </div>
      </div>
      <a href="?theme=dark" class="nav-link px-0 hide-theme-dark" title="Enable dark mode" data-bs-toggle="tooltip" data-bs-placement="bottom">
        <!-- Download SVG icon from http://tabler-icons.io/i/moon -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z" /></svg>
      </a>
      <a href="?theme=light" class="nav-link px-0 hide-theme-light" title="Enable light mode" data-bs-toggle="tooltip" data-bs-placement="bottom">
        <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><circle cx="12" cy="12" r="4" /><path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7" /></svg>
      </a>
      <div class="nav-item dropdown d-none d-md-flex me-3">
        <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1" aria-label="Show notifications">
          <!-- Download SVG icon from http://tabler-icons.io/i/bell -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" /><path d="M9 17v1a3 3 0 0 0 6 0v-1" /></svg>
          <span class="badge bg-red"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-end dropdown-menu-card">
          <div class="card">
            <div class="card-body">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad amet consectetur exercitationem fugiat in ipsa ipsum, natus odio quidem quod repudiandae sapiente. Amet debitis et magni maxime necessitatibus ullam.
            </div>
          </div>
        </div>
      </div>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
          <span class="avatar avatar-sm" style="background-image: url(<%= asset_path "admin/000m.jpg" %>)"></span>
          <div class="d-none d-xl-block ps-2">
            <div>Paweł Kuna</div>
            <div class="mt-1 small text-muted">UI Designer</div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
          <a href="#" class="dropdown-item">Set status</a>
          <a href="#" class="dropdown-item">Profile & account</a>
          <a href="#" class="dropdown-item">Feedback</a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">Settings</a>
          <%= button_to "Logout", admin_sign_out_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/admin/base/_secondary_navbar.html.erb
<div class="navbar-expand-md">
  <div class="collapse navbar-collapse" id="navbar-menu">
    <div class="navbar navbar-light">
      <div class="container-xl">
        <ul class="navbar-nav">
          <li class="nav-item <%= active_nav_item("admin/home") %>">
            <%= link_to admin_path, class: "nav-link" do %>
              <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="5 12 3 12 12 3 21 12 19 12" /><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" /><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" /></svg>
              </span>
              <span class="nav-link-title">
                Dashboard
              </span>
            <% end %>
          </li>
          <li class="nav-item <%= active_nav_item("admin/users") %>">
            <%= link_to admin_users_path, class: "nav-link" do %>
              <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><circle cx="9" cy="7" r="4"></circle><path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path><path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path></svg>
              </span>
              <span class="nav-link-title">
                Users
              </span>
            <% end %>
          </li>
        </ul>
        <div class="my-2 my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-last"></div>
      </div>
    </div>
  </div>
</div>

app/views/admin/base/_stylesheet_link_tags.html.erb
<!-- Tabler Core -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta24/dist/css/tabler.min.css">

<!-- Customize tabler here -->
<style>body {
  --tblr-body-bg: #f5f7fb;
}</style>

app/views/admin/home/index.html.erb
<%= content_for :title, "Dashboard" %>

<div class="page-body">
  <div class="container-xl">
    <h1>Admin::Home#index</h1>
    <p>Find me in app/views/admin/home/index.html.erb</p>
  </div>
</div>

app/views/admin/password_resets/edit.html.erb
<%= form_with(url: admin_password_reset_path, method: :patch, class: "card card-md") do |form| %>
  <div class="card-body">
    <h1 class="card-title text-center mb-4">Reset password</h1>

    <%= hidden_field_tag :token, params[:token] %>

    <div class="mb-3">
      <%= form.label :password, "New password", class: "form-label" %>
      <%= form.password_field :password, required: true, autofocus: true, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div>
      <%= form.label :password_confirmation, "Confirm new password", class: "form-label" %>
      <%= form.password_field :password_confirmation, required: true, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="form-footer">
      <%= form.submit "Save changes", class: "btn btn-primary w-100" %>
    </div>
  </div>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="form-group row mb-2">
    <%= form.label :email, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.email_field :email, autocomplete: "email", class: "form-control" %>
      <%= tag.div user.errors[:email].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row mb-2">
    <%= form.label :password, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.password_field :password, required: true, autocomplete: "new-password", class: "form-control" %>
      <%= tag.div user.errors[:password].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password_confirmation, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.password_field :password_confirmation, required: true, autocomplete: "new-password", class: "form-control" %>
      <%= tag.div user.errors[:password_confirmation].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-footer">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", admin_users_path, class: "btn btn-white" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "Editing user" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admin_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admin_users_path %></li>
    <li class="breadcrumb-item"><%= link_to @user.email, @user %></li>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "Users" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admin_path %></li>
  <% end %>

  <%= render "page_header_actions" do %>
    <%= link_to "Filters", "#offcanvas_filters", "data-bs-toggle": "offcanvas", class: "btn btn-white" %>
    <%= link_to "New user", new_admin_user_path, class: "btn btn-primary" %>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="table-responsive">
        <table class="table table-vcenter table-nowrap card-table table-striped">
          <thead>
            <tr>
              <th><%= sort_link @search, :id %></th>
              <th><%= sort_link @search, :email %></th>
              <th><%= sort_link @search, :created_at %></th>
              <th class="w-1"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.id, user %></td>
                <td><%= user.email %></td>
                <td><%= l(user.created_at, format: :long) %></td>
                <td>
                  <%= link_to "View", user, class: "btn btn-white btn-sm" %>
                  <%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-white btn-sm" %>
                  <%= link_to "Delete", user, class: "btn btn-white btn-sm", data: { method: :delete, confirm: "Are you sure?" } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex align-items-center fs-5">
        <div class="d-none d-md-block">
          <div>Download: <%= link_to "CSV", admin_users_path(format: :csv, q: request.params[:q]) %></div>
          <%== pagy_info(@pagy) %>
        </div>
        <div class="ms-auto">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="offcanvas_filters" tabindex="-1" class="offcanvas offcanvas-end">
  <div class="offcanvas-header">
    <h2 class="offcanvas-title">Filters</h2>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
  </div>
  <%= search_form_for @search, class: "offcanvas-body" do |f| %>
    <%= f.label :email_cont, class: "form-label" %>
    <%= f.text_field :email_cont, class: "form-control mb-3" %>

    <%= f.label :created_at, class: "form-label" %>
    <div class="d-flex gap-1 mb-3">
      <%= f.date_field :created_at_gteq, class: "form-control" %>
      <%= f.date_field :created_at_lteq, class: "form-control" %>
    </div>

    <%= f.submit "Filter", class: "btn btn-primary" %>
    <%= link_to "Clear Filter", admin_users_path, class: "btn btn-white" %>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "New user" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admin_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admin_users_path %></li>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: @user.email do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admin_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admin_users_path %></li>
  <% end %>

  <%= render "page_header_actions" do %>
    <%= link_to "Edit user", edit_admin_user_path(@user), class: "btn btn-primary" %>
    <%= link_to "Delete user", @user, class: "btn btn-white", data: { method: :delete, confirm: "Are you sure?" } %>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">User details</h3>
      </div>
      <div class="card-body">
        <dl class="row">
          <dt class="col-md-3">Email</dt>
          <dd class="col-md-9"><%= @user.email %></dd>

          <dt class="col-md-3">Created at</dt>
          <dd class="col-md-9"><%= l(@user.created_at, format: :long) %></dd>

          <dt class="col-md-3">Updated at</dt>
          <dd class="col-md-9"><%= l(@user.updated_at, format: :long) %></dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>